sudo: required
dist: trusty
language: node_js
node_js:
  - 7

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm i -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run e2e

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  on:
    tags: true

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm ./systelab.github.io/components/*
    cp ./dist/* ./systelab.github.io/components
    sed -i -e "s~base href=\"/\"~base href=\"/components/\"~g" ./systelab.github.io/components/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
  fi
